_target_: src.models.m_beta_vae_module.beta_VAEModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  
  factor: 0
  patience: 10
  
latent_dim: 4

encoder_dims:
  - 128
  - 64
  - 32
decoder_dims:
  - 8
  - 16
  - 32

beta : 1e-1

activation : "LeakyReLU"

predict_log : False

# non standard
input_dim: null