_target_: src.models.m_beta_vae_module.beta_VAEModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  
  factor: 0
  patience: 10
  
input_dim: null

latent_dim: 16

encoder_dims:
  - 256 
  - 124
  - 64
decoder_dims:
  - 64
  - 124
  - 256

beta : 1

predict_log : False
