_target_: src.models.mvae_module_ss_corrected.MVAEModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.0001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  
  factor: 0
  patience: 10
  
input_dim: null

latent_dim: 32

beta : 0.2

n_experts: 6

hidden_size: 256

prediction_length: 8

