# @package _global_

defaults:
  - _self_

  - data: lafan.yaml
  - model: beta_vae.yaml
  - logger: wandb.yaml # set logger here or use command line (e.g. `python train.py logger=tensorboard`)
  - trainer: gpu.yaml
  - paths: default.yaml
  - extras: default.yaml
  - hydra: default.yaml

task_name: "eval"

tags: ["dev"]

# passing checkpoint path is necessary for evaluation
ckpt_path: ${paths.log_dir}/train/runs/2023-05-02_16-15-47/checkpoints/epoch_009.ckpt

