defaults:
  - _self_

  - data: lafan.yaml
  - model: beta_vae.yaml
  - trainer: gpu.yaml
  - paths: default.yaml
  - hydra: default.yaml

base_pose :
  0: "latent0_pose"
  1: "T_pose"


task_name: "visualize"

tags: ["dev"]

# passing checkpoint path is necessary for inference
ckpt_path: ${paths.current_dir}/last.ckpt
