defaults:
  - _self_
  - data: lafan.yaml
  - model: pose_vae/beta_vae.yaml
  - callbacks: default.yaml
  - logger: wandb.yaml # set logger here or use command line (e.g. `python train.py logger=tensorboard`)
  - trainer: gpu.yaml
  - paths: default.yaml
  - extras: default.yaml
  - hydra: default.yaml


task_name: "infer"

tags: ["dev"]

# passing checkpoint path is necessary for inference
ckpt_path: ${paths.current_dir}/last.ckpt
