_target_: src.models.beta_vae_module_rot6d_modular_arch.beta_VAEModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  
  factor: 0
  patience: 10
  
input_dim: null

latent_dim: 8

beta : 0.002

encoder:
  _target_: src.models.components.simple_encoder.SimpleEncoder
  lin1_dim: 256
  output_dim: 64
  depth: 2

decoder:
  _target_: src.models.components.simple_decoder.SimpleDecoder
  latent_dim: ${model.latent_dim}
  lin1_dim: 64
  depth: 2

